name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18.1"
      - name: Install md
        run: go get github.com/ruggi/md@latest
      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: "17"
      - name: Install Sass
        run: npm i -g sass
      - name: Build
        run: md build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.md/out
